parameters:
  http_server.port: "8080"

services:

    React\EventLoop\Factory: ~

    React\EventLoop\LoopInterface:
        class: React\EventLoop\LoopInterface
        factory: ['@React\EventLoop\Factory', 'create']

    react.loop:
        alias: React\EventLoop\LoopInterface
        public: true

    React\Socket\Server:
        class: React\Socket\Server
        arguments: ["0.0.0.0:%http_server.port%", '@react.loop']

    react.socket.server: '@React\Socket\Server'

    http_foundation.factory:
        class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory

    diactoris.factory:
        class: Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory

    inisire\ReactBundle\Server\Server:
        class: inisire\ReactBundle\Server\Server
        arguments:
          - "@react.loop"
          - "@react.socket.server"
          - "@kernel"
          - "@http_foundation.factory"
          - "@diactoris.factory"
          - "@logger"

    react.http.server:
        alias: inisire\ReactBundle\Server\Server
        public: true

