services:

    React\EventLoop\Factory: ~

    React\EventLoop\LoopInterface:
        class: React\EventLoop\LoopInterface
        factory: ['@React\EventLoop\Factory', 'create']

    react.loop:
        alias: React\EventLoop\LoopInterface
        public: true

    react.socket.server:
        class: React\Socket\Server
        arguments: ["0.0.0.0:8080", '@react.loop']

    http_foundation.factory:
        class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory

    diactoris.factory:
        class: Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory

    react.http.server:
        public: true
        class: inisire\ReactBundle\Server\Server
        arguments:
          - "@react.loop"
          - "@react.socket.server"
          - "@kernel"
          - "@http_foundation.factory"
          - "@diactoris.factory"
          - "@monolog.logger"

    inisire\ReactBundle\Threaded\WorkerPoolFactory:
        class: inisire\ReactBundle\Threaded\WorkerPoolFactory
        arguments: ['%kernel.project_dir%/vendor/autoload.php', '@inisire\ReactBundle\Threaded\KernelFactoryInterface']

    inisire\ReactBundle\Threaded\MonitoredPool:
        class: inisire\ReactBundle\Threaded\MonitoredPool
        factory: ['@inisire\ReactBundle\Threaded\WorkerPoolFactory', "create"]

    worker.pool:
        public: true
        alias: inisire\ReactBundle\Threaded\MonitoredPool

    inisire\ReactBundle\Threaded\PoolMonitor:
        class: inisire\ReactBundle\Threaded\PoolMonitor
        public: true
        arguments: ['@React\EventLoop\LoopInterface', '@inisire\ReactBundle\Threaded\MonitoredPool', '@Psr\Log\LoggerInterface']

