services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  inisire\ReactBundle\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # Additional definitions
  React\EventLoop\Factory: ~
  Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory: ~
  Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory: ~
  inisire\ReactBundle\Server\HttpServer: ~
  GuzzleHttp\Psr7\HttpFactory: ~

  React\EventLoop\LoopInterface:
    factory: ['React\EventLoop\Loop', 'get']

  # Aliases
  Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface:
    alias: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory

  Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
    alias: inisire\ReactBundle\HttpFoundation\Factory\PsrHttpFactory

  Psr\Http\Message\ServerRequestFactoryInterface:
    alias: GuzzleHttp\Psr7\HttpFactory

  Psr\Http\Message\StreamFactoryInterface:
    alias: GuzzleHttp\Psr7\HttpFactory

  Psr\Http\Message\UploadedFileFactoryInterface:
    alias: GuzzleHttp\Psr7\HttpFactory

  Psr\Http\Message\ResponseFactoryInterface:
    alias: GuzzleHttp\Psr7\HttpFactory


